import os

from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

USE_REAL_LLM = API_KEY is not None

if USE_REAL_LLM:
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel("gemini-1.5-flash")


def generate_fallback(
    prediction,
    confidence,
    heart_rate,
    risk_score
):

    return f"""
## Summary

The uploaded fingertip video was analyzed using the VasoScan AI cardiovascular screening pipeline.

The model identified waveform characteristics associated with a **{prediction}** result. The overall confidence level was **{confidence}%**, indicating a moderate level of certainty in the prediction.

## Clinical Interpretation

The extracted vascular waveform was evaluated for patterns that may be associated with cardiovascular abnormalities. The observed signal characteristics contributed to the model's assessment and overall risk estimation.

This result should be considered a screening outcome and not a definitive clinical finding.

## Health Guidance

- Maintain a heart-healthy lifestyle with regular physical activity.
- Monitor cardiovascular symptoms such as chest discomfort, unusual fatigue, or shortness of breath.
- Consider consulting a healthcare professional for further evaluation if symptoms are present or concerns persist.

## Disclaimer

This screening result is generated by an AI-based analysis system and is intended for informational purposes only. It should not be considered a medical diagnosis or a substitute for professional medical advice.
""".strip()


def generate_summary(
    prediction,
    confidence,
    heart_rate,
    risk_score
):

    if not USE_REAL_LLM:
        return generate_fallback(
            prediction,
            confidence,
            heart_rate,
            risk_score
        )

    try:

        prompt = f"""
You are a professional cardiovascular health AI assistant.

Screening Result:

Prediction: {prediction}
Confidence: {confidence}%
Heart Rate: {heart_rate} BPM
Risk Score: {risk_score}/100

Generate a report using EXACTLY this structure.

## Summary
Provide a concise overview of the screening result in 2-3 sentences.

## Clinical Interpretation
Explain in simple and patient-friendly language what the result may indicate.
Focus on interpretation rather than repeating raw numbers.

## Health Guidance
Provide exactly 3 practical recommendations.

## Disclaimer
State that this screening result is not a medical diagnosis and should not replace professional medical advice.

Rules:
- Use professional medical-style language.
- Keep the report concise.
- Do not repeat the metrics as bullet points.
- Do not repeat Prediction, Confidence, Heart Rate, or Risk Score multiple times.
- Focus on interpretation and guidance.
- Use markdown headings exactly as specified.
"""

        response = model.generate_content(prompt)

        if response and response.text:
            return response.text.strip()

        return generate_fallback(
            prediction,
            confidence,
            heart_rate,
            risk_score
        )

    except Exception as e:

        print("Gemini Error:", e)

        return generate_fallback(
            prediction,
            confidence,
            heart_rate,
            risk_score
        )